version: 2
jobs:
    build:
        branches:
            only:
                - master
        docker:
            - image: circleci/node:stretch
        steps:
            - checkout
            - run:
                name: Generating universe.json file
                command: node generateData.js
            - run:
                name: Cloning universe-landing repository
                command: |
                    mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
                    git clone git@github.com:Astrocoders/universe-landing.git
            - run:
                name: Moving universe.json to universe-landing
                command: mv universe.json universe-landing/data/universe.json
            - run:
                name: Adding who I am to the project
                command: git config --global user.email "jeffersonhcarvalho@gmail.com" && git config --global user.name Jefferson Carvalho”
            - run:
                name: Adding, commiting and pushing changes to origin
                command:
                    cd universe-landing/data && git add universe.json && git commit -m "update universe.json" && git push origin develop
            - run:
                name: Deleting local copy of universe-landing
                command: rm -rf universe-landing
